"""
Auto-detecting loader for the credit-card-fraud Kaggle datasets.

Supports:
1. nelgiriyewithana/credit-card-fraud-detection-dataset-2023 (creditcard_2023.csv) -- 568K rows, balanced
2. mlg-ulb/creditcardfraud (creditcard.csv) -- 284K rows, 0.172% fraud
3. Synthetic fallback (creditcard_synthetic.csv) generated by 00_generate_synthetic.py

Drops `id` / `Time` so downstream code sees a uniform schema:
    [V1, V2, ..., V28, Amount, Class]
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# Files we look for, in priority order.
KNOWN_FILES = [
    ("creditcard_2023.csv", "kaggle_2023_balanced"),
    ("creditcard.csv", "kaggle_ulb_original"),
    ("creditcard_synthetic.csv", "synthetic_fallback"),
]

FEATURE_COLS = [f"V{i}" for i in range(1, 29)] + ["Amount"]
TARGET_COL = "Class"


@dataclass
class LoadedDataset:
    """Container for a loaded fraud dataset."""

    name: str  # one of: kaggle_2023_balanced, kaggle_ulb_original, synthetic_fallback
    df: pd.DataFrame  # full DataFrame after dropping id/Time
    feature_cols: list[str]
    target_col: str
    n_rows: int
    n_fraud: int
    fraud_rate: float
    is_balanced: bool

    def features(self) -> np.ndarray:
        """Return feature matrix as float64 array."""
        return self.df[self.feature_cols].to_numpy(dtype=np.float64)

    def labels(self) -> np.ndarray:
        """Return labels as int64 array."""
        return self.df[self.target_col].to_numpy(dtype=np.int64)

    def summary(self) -> str:
        return (
            f"Dataset: {self.name}\n"
            f"  rows         : {self.n_rows:,}\n"
            f"  fraud rows   : {self.n_fraud:,} ({self.fraud_rate * 100:.4f}%)\n"
            f"  features     : {len(self.feature_cols)} ({self.feature_cols[0]}..{self.feature_cols[-1]})\n"
            f"  is_balanced  : {self.is_balanced}"
        )


def find_first_available(data_dir: Path = DATA_DIR) -> tuple[Path, str]:
    """Return (path, name) of the first dataset file found in priority order."""
    for filename, name in KNOWN_FILES:
        path = data_dir / filename
        if path.exists():
            return path, name
    raise FileNotFoundError(
        f"No dataset CSV found in {data_dir}. Expected one of: "
        + ", ".join(f for f, _ in KNOWN_FILES)
        + ". See data/README.md for download instructions."
    )


def load(
    data_dir: Path = DATA_DIR,
    prefer: str | None = None,
    nrows: int | None = None,
) -> LoadedDataset:
    """
    Load the first available fraud dataset.

    Args:
        data_dir: folder containing the CSV(s).
        prefer: optional dataset name to prefer if multiple are present
                ("kaggle_2023_balanced", "kaggle_ulb_original", "synthetic_fallback").
        nrows: optional row cap for fast iteration / smoke tests.

    Returns:
        LoadedDataset with a uniform schema (V1..V28, Amount, Class).
    """
    data_dir = Path(data_dir)
    if prefer is not None:
        # Try preferred first; otherwise fall back to default search order.
        for filename, name in KNOWN_FILES:
            if name == prefer and (data_dir / filename).exists():
                path, dataset_name = data_dir / filename, name
                break
        else:
            logger.warning("Preferred dataset %s not found; falling back to default search.", prefer)
            path, dataset_name = find_first_available(data_dir)
    else:
        path, dataset_name = find_first_available(data_dir)

    logger.info("Loading %s from %s", dataset_name, path)
    df = pd.read_csv(path, nrows=nrows)

    # Drop id / Time -- they leak temporal structure or are pure indices.
    for drop_col in ("id", "Time"):
        if drop_col in df.columns:
            df = df.drop(columns=[drop_col])

    # Sanity check schema.
    missing = [c for c in FEATURE_COLS + [TARGET_COL] if c not in df.columns]
    if missing:
        raise ValueError(
            f"Dataset {path} is missing expected columns: {missing}. "
            f"Got columns: {list(df.columns)}"
        )

    df = df[FEATURE_COLS + [TARGET_COL]].copy()
    n_rows = len(df)
    n_fraud = int(df[TARGET_COL].sum())
    fraud_rate = n_fraud / n_rows if n_rows else 0.0
    is_balanced = 0.4 <= fraud_rate <= 0.6  # 2023 dataset is exactly balanced

    return LoadedDataset(
        name=dataset_name,
        df=df,
        feature_cols=FEATURE_COLS,
        target_col=TARGET_COL,
        n_rows=n_rows,
        n_fraud=n_fraud,
        fraud_rate=fraud_rate,
        is_balanced=is_balanced,
    )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    ds = load()
    print(ds.summary())
